### ISSUE TITLE
Question: Using Zuul for Internal Testing in Production 

### ISSUE THREAD

**Issue by ervansetiawan** [Netflix/zuul#136]
As part of our production deployment workflow, we would like to introduce a small cluster of new version of a service and we would like to perform an internal smoke test against that service before increasing the capacity and open it up to public.

My understanding is Zuul can be used for it but I can't figure out the best way to do it. 

Do we need to deploy the new version of the service using a different name in Eureka (e.g. ServiceX-V2) and have Zuul route the internal requests to that service?  

Or do we deploy a new Zuul and Eureka instance alongside the new service, leave that new Zuul out from the LoadBalancer and perform the internal test against that full stack?

**Comment by NiteshKant** [comment]
The first option of deploying the new service with a new name (VIP) in eureka is the standard way of achieving what you are trying to do. Zuul can then route specific requests to this new cluster and the remaining requests to the old cluster.

**Comment by afruchte** [comment]
If I have a new version of a micro service down the line (zuul->API->ms_a->ms_b->ms_c) like ms_b and I want initially only traffic from my test client to route to ms_b_v2 (if all goes well I will start allowing live traffic as well). How must I configure my system so that the calls from ms_a are routed to ms_b_v2 only for specific population. Do I have to have another Zuul between ms_a and ms_b?

**Comment by AlexWei2013** [comment]
I have same thing like @ervansetiawan. waiting some detail.
