### ISSUE TITLE
Zuul filter and customizing routing based on conditions

### ISSUE THREAD

**Issue by pradeepsingh1234** [Netflix/zuul#182]
Not sure where should I put this question. I have a zuul filter and I am trying to do conditional routing. I am looking for API where I can override route configuration and route the traffic. Example 
- 2 services ( Store and Customer)
- If request body has amount greater than $5000, then redirect traffic to Store  else customer.
- I am stuck and trying to find api on which I can customize routing. I tried ZuulRoute and didn't find how to use in spring cloud.

**Comment by mikeycohen** [comment]
Can you give a code example? I'm not sure what your question is.

**Comment by pradeepsingh1234** [comment]
if(price > 5000) {
// Go to service version 1- Customer 1.0


}
else {
// Go to service version 2- Customer 2.0
}

And I want to store and define all  route remotely, not in yaml file.

**Comment by NiteshKant** [comment]
@pradeepsingh1234 if you are using springcloud, then I am not sure what are the interfaces there, but otherwise, the filter code would look [something like this](https://github.com/Netflix/zuul/blob/2.x/zuul-netty-sample/src/main/filters/inbound/Routing.groovy#L44)

This is for 2.x branch though, which version are you trying?

**Comment by AlexWei2013** [comment]
@NiteshKant the "something like this" look is not found. Could you give some examples.
