### ISSUE TITLE
zuul 2 netty server example 

### ISSUE THREAD

**Issue by paperpunk** [Netflix/zuul#206]
Hello, 

I am considering zuul 2 as a potential dynamic routing solution and trying to get a simple netty-based example to work.

**scenario**
1. `/apache` in the request -> proxy to www.apache.org
2. `/npr` in the request -> proxy to www.npr.org
3. no parameter in the request -> proxy to www.netflix.com 

**steps**
1. assuming that _www.apache.org_, _www.npr.org_ and _www.netflix.com_ are considered **origins**, add the following to `zuul.properties` file:
   `zuul.origins=apache=www.apache.org,npr=www.npr.org,netflix=www.netflix.com`
2. in an inbound filter, analyze the request to determine whether it has `/npr` or `/apache` ([similar to this example](https://github.com/Netflix/zuul/blob/2.x/zuul-netty-sample/src/main/filters/inbound/Routing.groovy#L53)), and set the `routeVip` and endpoint filter accordingly

```
if ( request.getPath() == "/apache" ) {
  context.setRouteVIP( "apache" )
} else if ( request.getPath() == "/npr" ) {
  context.setRouteVIP( "npr" )
} else {
  context.setRouteVIP( "netflix" )
}

context.setEndpoint( "endpoint.ZuulNFRequest" )
```
1. in the endpoint filter, use the default NfProxyEndpoint to proxy to the appropriate endpoint

**questions**
1. judging by the fact that when I send a request to `localhost:7001` where the sample [netty server](https://github.com/Netflix/zuul/blob/2.x/zuul-netty-sample/src/main/java/com/netflix/zuul/NettySampleStartServer.java#L124) is running, I keep getting the default `hello world` response back, i am not setting this up correctly.  what am I doing wrong?
2. are there any examples of inbound filters that don't use the [origin's http client](https://github.com/Netflix/zuul/blob/2.x/zuul-netty-sample/src/main/filters/inbound/ExampleIOPreFilter.groovy#L33) but instead have a separate one? 
3. should I be setting the `context.setRouteHost()` along with the `routeVIP` for something like this to work? ([analogously to what zuul 1 does](https://github.com/Netflix/zuul/blob/1.x/zuul-simple-webapp/src/main/groovy/filters/pre/PreDecorationFilter.groovy#L46))
4. are _www.apache.org_, _www.npr.org_ and _www.netflix.com_ really **origins** here? if not, what are origins?

**Comment by VijithaEkanayake** [comment]
Hi,

Tried zuul 2 as a dynamic routing solution and wasn’t been able get simple netty-based example to work. I’m also facing the same issue described by paperpunk. Is there any references which we can refer to get this dynamic routing working?

When I send requests to Zuul, Only the static filter correctly invoked and gives the desired output. For all other configured routes, always receiving response helloworld response back. Can you help me to figure out What am I missing here?

Thanks,
Vijitha

**Comment by pataprogramming** [comment]
The issue here is that the `NettySampleStartServer` never actually looks at the list of the VIP mappings! It carefully parses out the list of origins, but just maps each of them to the "hello world" endpoint running on port 7002.

The code for loading the mappings in the VIPs is in `SimpleRRLoadBalancerFactory`, but this class is not actually referenced anywhere else in the sample server's code.

Perhaps I'm missing something, but it looks like you might have to override some things from `zuul-netty` in order to get the replacement load balancer factory patched in.

Here's a quick-and-dirty fix to get it working (needs comma-separated VIP mappings, not semi-colon-separated, and only takes one host per VIP.

  https://gist.github.com/pataprogramming/84b25f95c088ae29a097

A couple of other notes: 

- Yahoo is a terrible site to test with. Zuul leaves the `Host` header set to `localhost`, which will prevent many Internet sites from responding. Try pointing to http://httpbin.org for a more API-like test endpoint.

- If you try to view the proxied site through a browser, something in one of the `outbound` filters is messing with the request and confusing the browser so it only processes the first chunk. (This behavior doesn't seem to happen with `curl`.) I recommend removing or disabling the outbound filters while trying to get the server working.
