### ISSUE TITLE
Ability to use http proxy for requests

### ISSUE THREAD

**Issue by warroyo** [Netflix/zuul#303]
Is it possible to use an http proxy with zuul proxy. for example I am in a limited access network that has to go through a  standard http proxy to access the internet. I woudl like to use zuul proxy as a gateway to a service on the internet so I would need to have the requests go through the http proxy.

I have tried setting the standard `-Dhttp.proxy* ` options but the request still do not seem to rout through the proxy. Does zuul have an option to set a proxy as well as a noProxy for routing requests?

**Comment by spdqbr** [comment]
This is a result of the zuul dependency on spring-cloud-netflix 1.1.5 : https://github.com/spring-cloud/spring-cloud-netflix/issues/332

There was a fix to spring-cloud-netflix included with releases after 1.2.0 which makes it respect the -Dhttp[s].proxy* setttings.  Including version 1.2.0 as a compile dependency for the project appears to have resolved the issue for us, but may have unintended consequences since zuul expects 1.1.5.
