### ISSUE TITLE
Please mention in docs that Zuul doesn't support long-lived connections

### ISSUE THREAD

**Issue by ollie-o** [Netflix/zuul#471]
Our team has been having a very stressful time resolving a bug where a few long-lived connections would cause our application to stop responding to requests.

Finally, after many many hours of our whole team working to resolve it, we came across [this comment on a Spring proxy GitHub issue](https://github.com/spring-cloud/spring-cloud-netflix/issues/2385#issuecomment-339120181):

> Zuul is not built for any sory of long-lived connections, so this does not surprise me.

> Long lived connections in zuul are generally a problem.

If Zuul really does not support long-lived connections, please mention this somewhere obvious in your documentation. It's frustrating to learn this only after setting everything up and stress-testing the application.

**Comment by artgon** [comment]
Can you give more details? Steps to reproduce? Is this about Zuul 1 (what Spring uses) or Zuul 2?

**Comment by oliverodaa** [comment]
We have fixed our issue by switching from Spring to Nginx. We had some POST requests that (by design) do not receive responses for minutes at a time. That's what I meant by 'long lived'.

@spencergibb in the linked thread seemed to mention that "Long lived connections in zuul are generally a problem." as if it is common knowledge.

Is he wrong?

If it is common knowledge that Zuul 1 does not support long-lived connections, then it should be documented, right?
