### ISSUE TITLE
how to run the push sample

### ISSUE THREAD

**Issue by nguyennp** [Netflix/zuul#554]
I just download and do the gradlew run command to run the sample. Things i got is the screen saying "Zuul Sample: finished startup. Duration = 19637 ms".  http://localhost:7001/ shown error 502.

Read the java code of the sample but still don't now how to do next to see what the sample do.
Please help to show what i have to do to check what the sample intended to show.

**Comment by raksoras** [comment]
You need to make two changes. 

1. By default Zuul Push sample port will open a WebSocket listening port on 7008 and not 7001. You can modify default by specifying system property zuul.server.push.port (for example, -Dzuul.server.push.port=7002)

2. You can't use simple HTTP protocol to connect to the push port since it is expecting WebSocket upgrade request. You'll have to connect it using some sort of WebSocket client. Python, Node.js, Java all have WebSocket clients that you can use to test it

**Comment by nguyennp** [comment]
Thanks, I was able to run websocket by changing SERVER_TYPE = ServerType.WEBSOCKET in the code.
