### ISSUE TITLE
How to run a standalone Jar

### ISSUE THREAD

**Issue by amir-hg** [Netflix/zuul#750]
Hello
i read the wiki of github and understood how to run it with ./gradlew run 
but now i would like to create a runnable standalone jar from zuul-sample and run it like " java -jar zuul-sample.jar" 
i noticed that there is jar file on build/libs but it does not include main manifest (no main manifest attribute, in zuul-sample/build/libs/zuul-sample-2.1.8-SNAPSHOT.jar)
so how i could run jar file

I tried shadow plugin and jar attributes but none of them worked for me
I need a clean docs to config and create a jar file

**Comment by rnacharya** [comment]
Facing the same issue. Specified the main class, Bootstrap explicitly using command line. 
I get this error

rnacharya libs % java -cp zuul-sample-2.1.8-SNAPSHOT.jar com/netflix/zuul/sample/Bootstrap
Error: Unable to initialize main class com.netflix.zuul.sample.Bootstrap
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Module
